# Generated by Django 3.0.2 on 2020-12-20 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmshop', '0002_catolog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catolog',
            new_name='Catalog',
        ),
    ]
