# Generated by Django 3.0.2 on 2020-12-22 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmshop', '0003_auto_20201221_0153'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catalog',
            new_name='CatalogInfo',
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='tagline',
            field=models.CharField(max_length=150, verbose_name='Слоган'),
        ),
    ]
