# Generated by Django 3.0.2 on 2020-12-22 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmshop', '0005_category_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
