# Generated by Django 3.0.2 on 2020-12-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmshop', '0007_auto_20201222_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='active_substance',
            field=models.CharField(max_length=500, null=True, verbose_name='Действующее вещество'),
        ),
        migrations.AddField(
            model_name='product',
            name='drug_action',
            field=models.CharField(max_length=500, null=True, verbose_name='Действие препарата'),
        ),
        migrations.AddField(
            model_name='product',
            name='mode_of_application',
            field=models.CharField(max_length=500, null=True, verbose_name='Способ применение'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена(сум)'),
        ),
        migrations.AddField(
            model_name='product',
            name='release_forms',
            field=models.CharField(max_length=500, null=True, verbose_name='Формы выпуска'),
        ),
        migrations.AddField(
            model_name='product',
            name='structure',
            field=models.TextField(null=True, verbose_name='Состав'),
        ),
    ]
