# Generated by Django 3.0.2 on 2020-12-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmshop', '0008_auto_20201222_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=130, null=True, unique=True),
        ),
    ]
