# Generated by Django 3.0.2 on 2020-12-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmshop', '0010_auto_20201222_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='photo',
            field=models.ImageField(null=True, upload_to='articles/', verbose_name='Фото'),
        ),
    ]
