# Generated by Django 3.0.2 on 2020-12-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmshop', '0011_article_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tagline',
            field=models.CharField(max_length=200, null=True, verbose_name='Слоган'),
        ),
    ]
