# Generated by Django 3.0.2 on 2020-12-22 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmshop', '0012_article_tagline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовка')),
                ('video', models.FileField(null=True, upload_to='videos/', verbose_name='Фото')),
                ('tagline', models.CharField(max_length=200, null=True, verbose_name='Слоган')),
                ('content', models.TextField(verbose_name='Текст')),
                ('slug', models.SlugField(max_length=200, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Видео ролик',
                'verbose_name_plural': 'Видео ролики',
            },
        ),
    ]
