# Generated by Django 3.0.2 on 2020-12-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmshop', '0013_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='company_year_en',
            field=models.CharField(max_length=100, null=True, verbose_name='История нашего бизнеса ...'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='company_year_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='История нашего бизнеса ...'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='company_year_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='История нашего бизнеса ...'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='content_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='content_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='content_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='tagline_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Слоган'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='tagline_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Слоган'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='tagline_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Слоган'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_ru',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_uz',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='article',
            name='tagline_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Слоган'),
        ),
        migrations.AddField(
            model_name='article',
            name='tagline_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Слоган'),
        ),
        migrations.AddField(
            model_name='article',
            name='tagline_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Слоган'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовка'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовка'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовка'),
        ),
        migrations.AddField(
            model_name='cataloginfo',
            name='content_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='cataloginfo',
            name='content_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='cataloginfo',
            name='content_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='cataloginfo',
            name='tagline_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Слоган'),
        ),
        migrations.AddField(
            model_name='cataloginfo',
            name='tagline_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Слоган'),
        ),
        migrations.AddField(
            model_name='cataloginfo',
            name='tagline_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Слоган'),
        ),
        migrations.AddField(
            model_name='cataloginfo',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='cataloginfo',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='cataloginfo',
            name='title_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='consulting',
            name='content_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='consulting',
            name='content_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='consulting',
            name='content_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='consulting',
            name='tagline_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Слоган'),
        ),
        migrations.AddField(
            model_name='consulting',
            name='tagline_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Слоган'),
        ),
        migrations.AddField(
            model_name='consulting',
            name='tagline_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Слоган'),
        ),
        migrations.AddField(
            model_name='consulting',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='consulting',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='consulting',
            name='title_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='product',
            name='active_substance_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Действующее вещество'),
        ),
        migrations.AddField(
            model_name='product',
            name='active_substance_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='Действующее вещество'),
        ),
        migrations.AddField(
            model_name='product',
            name='active_substance_uz',
            field=models.CharField(max_length=500, null=True, verbose_name='Действующее вещество'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описания'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описания'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Описания'),
        ),
        migrations.AddField(
            model_name='product',
            name='drug_action_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Действие препарата'),
        ),
        migrations.AddField(
            model_name='product',
            name='drug_action_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='Действие препарата'),
        ),
        migrations.AddField(
            model_name='product',
            name='drug_action_uz',
            field=models.CharField(max_length=500, null=True, verbose_name='Действие препарата'),
        ),
        migrations.AddField(
            model_name='product',
            name='mode_of_application_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Способ применение'),
        ),
        migrations.AddField(
            model_name='product',
            name='mode_of_application_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='Способ применение'),
        ),
        migrations.AddField(
            model_name='product',
            name='mode_of_application_uz',
            field=models.CharField(max_length=500, null=True, verbose_name='Способ применение'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Названия'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Названия'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Названия'),
        ),
        migrations.AddField(
            model_name='product',
            name='release_forms_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Формы выпуска'),
        ),
        migrations.AddField(
            model_name='product',
            name='release_forms_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='Формы выпуска'),
        ),
        migrations.AddField(
            model_name='product',
            name='release_forms_uz',
            field=models.CharField(max_length=500, null=True, verbose_name='Формы выпуска'),
        ),
        migrations.AddField(
            model_name='product',
            name='structure_en',
            field=models.TextField(null=True, verbose_name='Состав'),
        ),
        migrations.AddField(
            model_name='product',
            name='structure_ru',
            field=models.TextField(null=True, verbose_name='Состав'),
        ),
        migrations.AddField(
            model_name='product',
            name='structure_uz',
            field=models.TextField(null=True, verbose_name='Состав'),
        ),
        migrations.AddField(
            model_name='video',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='video',
            name='content_ru',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='video',
            name='content_uz',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='video',
            name='tagline_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Слоган'),
        ),
        migrations.AddField(
            model_name='video',
            name='tagline_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Слоган'),
        ),
        migrations.AddField(
            model_name='video',
            name='tagline_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Слоган'),
        ),
        migrations.AddField(
            model_name='video',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовка'),
        ),
        migrations.AddField(
            model_name='video',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовка'),
        ),
        migrations.AddField(
            model_name='video',
            name='title_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовка'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(null=True, upload_to='videos/', verbose_name='Видео'),
        ),
    ]
